### ISSUE TITLE
SMB volumes are not refreshing view on file change

### ISSUE THREAD

**Issue by nitrostudios** [mikekazakov/nimble-commander#100]
When I have opened SMB volume and there is a file change, e.g. file deleted on the server or new file created on the server side, the view does not refresh/update in NC. Have to manually refresh with keys Cmd+R. Works correctly in Finder, Commander One, Double Commander and Forklift.

macOS 12.6.6
NC 1.5.0 Build 3981

**Comment by mikekazakov** [comment]
Thanks for reporting, I was finally able to reproduce the issue and found a bug in NC.

**Comment by nitrostudios** [comment]
Great, thank you very much, looking forward to the new preview version!

**Comment by mikekazakov** [comment]
I aim to set up nightly builds pretty soon, so there will be no need to wait for preview releases.
