### ISSUE TITLE
Random bug when navigation folders with mouse cursor

### ISSUE THREAD

**Issue by nitrostudios** [mikekazakov/nimble-commander#101]
There is a random bug that causes problem with navigation when using the mouse cursor, as it sometimes does not detect the correct cursor position and therefore navigates into other folder (or selects other file) than one directly under the cursor.

NC 1.5.0 Build 3981

**Comment by mikekazakov** [comment]
Any way to reliably reproduce?

**Comment by nitrostudios** [comment]
Yes, actually I can trigger it quite easily on my side. Go to any subfolder, like /Library/Application Support/Apple/ParentalControls/ and then position your cursor in the first row where is go to parent folder "..". And now, don't move the cursor, just double click to go up and up and there will be time when either, you will have to double click several times to go to the parent folder, or you will enter the random folder that is not currently highlighted and not under cursor.

**Comment by mikekazakov** [comment]
I can confirm that the issue is reproducible on my side, good catch - thank you!

**Comment by nitrostudios** [comment]
Thank you for confirmation!

**Comment by mikekazakov** [comment]
There shouldn't be anymore situations when the cursor position ends up being invalid in the Brief view mode because of multiple mouse clicks and changing the directory at the same time.
