### ISSUE TITLE
How to use Enter on numeric keyboard?

### ISSUE THREAD

**Issue by nitrostudios** [mikekazakov/nimble-commander#103]
How can I use Enter on numeric keyboard the same way as the regular Enter, please? Currently, can't use numeric one to navigate folders, files... Thank you very much for your help!

**Comment by mikekazakov** [comment]
But those key emit different characters/keycodes, aren't they?
Enter emits Unicode 13 / Key Code 23 and that key on the numeric keyboard emits Unicode 3 / Key Code 76.
To reassign that key you can use some app like Karabiner.

**Comment by nitrostudios** [comment]
Thank you! Yes, I know, but to remap the key globally does not really work in my case. Anyway, just wanted to asked about the possibility to use it just in the NC, that's all:)

**Comment by mikekazakov** [comment]
Generally it'd be good to have a generic option to assign more than one key to an action, which would implicitly solve this question. But that's a much larger and not directly connected task, so it'll close this issue for now.
