### ISSUE TITLE
Incorrect restoration of directory permissions from archive

### ISSUE THREAD

**Issue by alexey-lysiuk** [mikekazakov/nimble-commander#104]
Consider the following shell script.
```sh
#!/bin/sh
mkdir testdir
touch testdir/testfile
chmod u-w testdir 
tar -cf test.tar testdir
```

Attempt to extract archive `test.tar` fails to the following error.
> **Failed to open a destination file**
> Error: The operation couldn't be completed. Permission denied.

Usage of different archive format, e.g. by replacing the last line of the script with `zip -r test.zip testdir`, leads to the same error.

It seems like directory permissions are set before files extraction. Corresponding console tools, `tar` and `unzip`, restore permissions correctly.

**Comment by mikekazakov** [comment]
Thanks for the minimalistic repro!
Indeed it causes problems for the existing implementation - currently it sets up the permissions and other flags immediately after creating a new directory (https://github.com/mikekazakov/nimble-commander/blob/d12ac94696e87fa448321cbe10dd51c894a65026/Source/Operations/source/Copying/CopyingJob.cpp#L1976).
Should be fixable by adding an additional step that would traverse the targets and change permissions where necessary.
