### ISSUE TITLE
1px line below titlebar not updated when changing OS appearance from light to dark and vice versa

### ISSUE THREAD

**Issue by vladstudio** [mikekazakov/nimble-commander#115]
Demo:

https://github.com/mikekazakov/nimble-commander/assets/914320/694f8af0-e3dc-4bb0-b156-090d750132a0

note the glitchy light line below the titlebar. 
Restarting the app fixes this.

**Comment by mikekazakov** [comment]
Should be fixed now, thanks for reporting.
