### ISSUE TITLE
not 100% perfect alignment of Rename in place 

### ISSUE THREAD

**Issue by vladstudio** [mikekazakov/nimble-commander#119]
I know I know but it bugs me every time!

<img width="368" alt="image" src="https://github.com/mikekazakov/nimble-commander/assets/914320/88668197-3bc6-4b44-95ee-a6816067db15">

2px on top, 1px on bottom. Heelp :-)

**Comment by mikekazakov** [comment]
Thanks for the report, should be fixed now.
