### ISSUE TITLE
Feature Request: Choose directory (F1/F2) with cursor keys

### ISSUE THREAD

**Issue by mikekazakov** [mikekazakov/nimble-commander#187]
### Discussed in https://github.com/mikekazakov/nimble-commander/discussions/162

<div type='discussions-op-text'>

<sup>Originally posted by **Amadeus6767** March 17, 2024</sup>
Hi,

I hope it is a simple request and I have the feeling it worked before. But now it does not.
If I press "F1" to search for a directory/ harddisk and then start typing - nimble commander finds all the devices in which the phrase appears.

For example. I Have 6 harddisk named : Foto_1, Foto_2, Foto_3, Foto_4, 8TB_1_Foto, 8TB_2_Foto
If I type "8TB", nimble commander shows me the last 2 devices.

**Now the request:** I would like to choose the second device "8TB_2_Foto", JUST by pressing the "Cursor DOWN" key.

That does not work. Would it be possible to implement that feature?

Regards

Amadeus6767

</div>

**Comment by necrevistonnezr** [comment]
Yes, I noticed too that the „Arrow down“ key doesn’t work anymore, also when trying to select a favorite form the list

**Comment by mikekazakov** [comment]
I'm writing a replacement component to not rely on the behaviour of NSMenu at all. Stay tuned :)

**Comment by mikekazakov** [comment]
New UI, currently in a branch https://github.com/mikekazakov/nimble-commander/tree/gh187, close to be merged into Main:
<img width="408" alt="Screenshot 2024-04-07 at 23 09 02" src="https://github.com/mikekazakov/nimble-commander/assets/7439287/cb664260-53f6-4f5b-b7ad-5c7ce4b4045e">

The same component is used for quick lists, which are going to be expanded soon: 
<img width="509" alt="Screenshot 2024-04-07 at 23 10 45" src="https://github.com/mikekazakov/nimble-commander/assets/7439287/3625ba5d-f057-41ca-9b42-7bf661946150">

**Comment by mikekazakov** [comment]
Fixed, please check the nightly builds.

**Comment by silicooon** [comment]
Thank you so much!!
