### ISSUE TITLE
When set as default File manager download links from browser doesn't work

### ISSUE THREAD

**Issue by piratx** [mikekazakov/nimble-commander#197]
### Version of Nimble Commander

v16, macOS 13.6.6

### Distribution Type

Downloaded directly from the website

### Expected Result

I am using Nimble Commander as my default file manager on my Mac. Finder is not available, i've quit it.
When I am downloading something on Safari (main browser) and using the little search icon next to it to "find" or "show" it on Finder/or Nimble in my case.  It gives me the error I've pasted below.

Also, when I am trying to cmd shift R on Music to give me the location of a music file it brings Nimble Commander in front but never gives me the right path or any path the song is put in, it just brings it in front.

If the above worked, it should give you the "file" path of each action! 
It should give you the path of the download current directory into Nimble Commander.

### Actual Result

<img width="252" alt="image" src="https://github.com/mikekazakov/nimble-commander/assets/242366/09625954-15c4-450c-944f-91abf7e9b459">

It gives the above error message.

### Steps to reproduce

You need to set Nimble as your default file manager. 

Use this command in terminal
`defaults write -g NSFileViewer -string info.filesmanager.Files`
you can undo it easy with
`defaults delete -g NSFileViewer`

After this, just download something with Safari and try to click the search icon on the download popup.
For Music, just go in Music add an mp3 file, or if you have one already try cmd shift R on it.

### Additional Information

Thank you so much, for all the hard work you do for this special app :)

**Comment by mikekazakov** [comment]
I've just checked it on my laptop (though running MacOS14). For me Safari successfully opens NC and it then focuses the downloaded file. Some context is missing from the picture.
