### ISSUE TITLE
Bash is not loading config files

### ISSUE THREAD

**Issue by mikekazakov** [mikekazakov/nimble-commander#21]
Another quick question about the built-in terminal: it does not seem to import .bashrc or .bash_profile.

**Comment by singalen** [comment]
For me, it did.
If it ever happens, it all boils down to startup mode and the docs: https://www.gnu.org/software/bash/manual/html_node/Bash-Startup-Files.html.

**Comment by mikekazakov** [comment]
Works as expected, closing the issue.
