### ISSUE TITLE
[Bug]: Unable to duplicate file that is being downloaded in NC

### ISSUE THREAD

**Issue by nitrostudios** [mikekazakov/nimble-commander#223]
### Version of Nimble Commander

1.6.0 (4061), macOS 12.6.6

### Distribution Type

Downloaded directly from the website

### Expected Result

Being to duplicate file that is being downloaded in NC, since it works in Finder and DC, for example.

### Actual Result

Unable to duplicate file that is being downloaded in NC:

Failed to read source file.
Error The operation couldn’t be completed. No such file or directory

### Steps to reproduce

1. start downloading the large file
2. try to duplicate the file

**Comment by mikekazakov** [comment]
What is the semantical expecation after duplicating a file that's being written to?

**Comment by nitrostudios** [comment]
For example, downloading a large video file when duplicating the content can be viewed (previewed) before the whole file is downloaded.

**Comment by mikekazakov** [comment]
Hm, that makes sense, didn't think of this use case. I'll take a look why NC refuses to copy such files.

But, for my understanding, the result of such copy will be corrupted to some extent anyway, right?

**Comment by nitrostudios** [comment]
Thank you for your time, appreciate it!

> But, for my understanding, the result of such copy will be corrupted to some extent anyway, right?

Yes, I believe so, since the duplicate contains only already downloaded information and the rest of the file is missing. But in case of video file, it can be previewed up to the point of data already downloaded (also depending on the codec and data stream).

**Comment by mikekazakov** [comment]
Found the problem, will try to cover with a unit test and fix it.
Apparently the logic didn't correctly processed such scenario and ended up reading more data than the algorithm expected, which caused it to go haywire afterwards.

**Comment by nitrostudios** [comment]
Thank you, Mike, appreciate it!

**Comment by mikekazakov** [comment]
Please try a nightly build.

**Comment by nitrostudios** [comment]
Thank you very much, Mike, that was really fast! it works correctly now :)
