### ISSUE TITLE
[Bug]: Incorrect directory permissions on .zip extracted content

### ISSUE THREAD

**Issue by alexey-lysiuk** [mikekazakov/nimble-commander#274]
### Confirmation

- [X] I have read the contributing guidelines

### Version of Nimble Commander

v1.6.0 (4077), macOS 14.4.1

### Distribution Type

Downloaded directly from the website

### Expected Result

Permissions restoration of directories extracted from .zip archive to `drwxr-xr-x`.

### Actual Result

Extracted directories have `d---------` permissions.

### Steps to reproduce

Create .zip archive **without directory entries** from command line.

```sh
mkdir temp
echo temp > temp/temp.txt
zip -rD temp.zip temp  # notice -D option: do not add directory entries
```

Upon extraction of `temp.zip`, e.g., by copying from one pane with the archive opened to another pane, permissions of `temp` directory are cleared.
```
...
d---------   3 user  staff      102 May 10 10:10 temp
...
```

Files and directories inside directory without an entry are extracted correctly, permissions are cleared though.

**Comment by mikekazakov** [comment]
Thank you for the detailed bug report, I'll try fix it ASAP.
