### ISSUE TITLE
[Bug]: Folder changes after loading file list

### ISSUE THREAD

**Issue by nitrostudios** [mikekazakov/nimble-commander#276]
### Confirmation

- [X] I have read the contributing guidelines

### Version of Nimble Commander

1.6.0 (4068), macOS 12.6.6

### Distribution Type

Downloaded directly from the website

### Expected Result

When entering folder with lot of file (400+) and then going 1 level up while the content of the folder is loading (spinning circle at the top right corner), the NC should not change the folder back to the one that was loading and should stay in the current folder.

### Actual Result

When entering folder with lot of file (400+) and then going 1 level up while the content of the folder is loading (spinning circle at the top right corner), the NC changes to the one that was loading.

Folder 1
- Folder 2
Folder 1
NC changes to folder 2 after a short while

### Steps to reproduce

1. Go to folder 1
2. Go to folder 2 with lot of files
3. Go back to folder 1
4. After a short while the NC changes the folder back to folder 2

**Comment by mikekazakov** [comment]
Thank you for the report, however there's not enough input to make it actionable.
Please provide a specific set of steps that needs to be followed to reliably reproduce the problem.
This may include generating these "Folder 1" and "Folder 2", including their contents, you can use shell scripts to create them.

**Comment by nitrostudios** [comment]
Yes, this is a bit difficult, since it's happening randomly, maybe once or twice a week, still trying to figure out what might be the cause, because it's not happening in specific folder. This morning it happened 5 times, I've restarted the Mac and can't trigger it now in the same folders.

**Comment by mikekazakov** [comment]
I understand that such occasions can be frustrating, but I absolutely don't have bandwidth to chase a random issue that happens once in a few days and is not reproducible. Closing now but feel free to reopen once it can be reliably reproduced.
