### ISSUE TITLE
[Bug]: NC slower to load folders than Finder or Double Commander or Forklift

### ISSUE THREAD

**Issue by nitrostudios** [mikekazakov/nimble-commander#277]
### Confirmation

- [X] I have read the contributing guidelines

### Version of Nimble Commander

1.6.0 (4068), macOS 12.6.6

### Distribution Type

Downloaded directly from the website

### Expected Result

NC should in theory load folders with the same speed as other file managers?

### Actual Result

NC slower to load folders than Finder or Double Commander or Forklift

### Steps to reproduce

1. Open folder with lot of files in NC
2. Open folder in DC or Finder, opens much faster

**Comment by mikekazakov** [comment]
More information is needed, please feel to reopen the issue with:
- reproducible setup that can be rolled out on a new machine;
- benchmark results.

**Comment by nitrostudios** [comment]
Now, since I've restarted the Mac, it loads the folders with many files faster like in other file managers... Is macOS slowing down after several hours of uptime? Before restart the same folder with 600 files it took 12 seconds to load, after restart 3 seconds... I don't understand.

**Comment by mikekazakov** [comment]
It should not, an uptime of multiple days or weeks an absolutely normal thing.
