### ISSUE TITLE
[Bug]: Search in change panel source menu

### ISSUE THREAD

**Issue by pwu7** [mikekazakov/nimble-commander#287]
### Confirmation

- [X] I have read the contributing guidelines

### Version of Nimble Commander

1.6.0

### Distribution Type

Downloaded from the Mac App Store (i.e. sandboxed)

### Expected Result

When I change a Panel source, I type "T51" in search field and get results with "T51"

### Actual Result

I type "T" and NC start search but when I hit 5 it switches to Favorite number 5

### Steps to reproduce

1. Hit F1
2. Type T5
3.

### Additional Information

It worked fine in previous versions

**Comment by mikekazakov** [comment]
This UX was changed in v1.6 - now numeric keys behave as hotkeys all the time, regardless of the search field state.

**Comment by pwu7** [comment]
Could you please add some options in settings to disable it? Or maybe hotkeys (1-9) might be reassigned or changed in Favorites settings menu? Since if you have any numeric characters in external volumes names you'll not be able to search them. It was very useful before and there is no sense to switch to favorites if you are already started to search

Thank you in advance!

**Comment by mikekazakov** [comment]
Ok, on a second thought this actually doesn't seem as a good idea.
I'll adjust this filtering behaviour to match v1.5.

**Comment by mikekazakov** [comment]
Your feedback would be valuable during development (before the version was released) - nightly builds had this re-written implementation of the popup and thus the different filtering logic for more than a month.

**Comment by pwu7** [comment]
> Ok, on a second thought this actually doesn't seem as a good idea. I'll adjust this filtering behaviour to match v1.5.

Thank you so much, I really appreciate it!

**Comment by mikekazakov** [comment]
> > Your feedback would be valuable during development (before the version was released) - nightly builds had this re-written implementation of the popup and thus the different filtering logic for more than a month.
> 
> I'd like to, but I don't know how to find compiled night builds - I've found only reports. And I'm not a professional developer to compile it on my own, I am just loyal NC user who stayed with your incredible software for a while :)

Hope this helps:
<img width="1233" alt="Screenshot 2024-06-04 at 21 28 59" src="https://github.com/mikekazakov/nimble-commander/assets/7439287/4685fbdf-c5d5-417c-b10f-9dce1ca91af5">


> And one more question.
> 
> I'm staying on NC 1.5 at a moment and I've just updated to macos 14.5 and up/down arrows stopped working while selecting volume in change volume dropdown menu. It works on NC 1.6 but I can't use it because the issue I've write you here (I have many volumes with numeric characters and I can't just rename all the volumes to keep them only alphabetic). And it still works on NC 1.5 with macos 13.6.7 on other mac. Is it macos update bug?

MacOS 14 overhauled the menu system and the hack NC relied upon stopped working. That hack was used for the filtering of the menu items in NC versions before 1.6.

**Comment by mikekazakov** [comment]
Should be fixed now.

**Comment by pwu7** [comment]
it works, thank you!
