### ISSUE TITLE
[Bug]: Cannot extract zip archive with Deflate64 compression method

### ISSUE THREAD

**Issue by alexey-lysiuk** [mikekazakov/nimble-commander#290]
### Confirmation

- [X] I have read the contributing guidelines

### Version of Nimble Commander

1.6.0 (4087)

### Distribution Type

Downloaded directly from the website

### Expected Result

File(s) are extracted from an archive.

### Actual Result

`Failed to read source file` error is reported.

### Steps to reproduce

Open any .zip archive that uses Deflate64 compression method, and try to extract any file from it.
For example, windows Explorer creates such archives when total data size exceeds 2 GiB.
On macOS, archive can be created with console 7-zip executable, `7zz a -mm=Deflate64 test.zip file file ...`.

**Comment by mikekazakov** [comment]
Is this compression supported by libarchive?

**Comment by alexey-lysiuk** [comment]
I guess, nothing changed since this report, https://github.com/libarchive/libarchive/issues/1863. It's kinda weird because open source tools support Deflate64 for compression and decompression. For example, `unzip` shipped with macOS handles this compression method just fine.

**Comment by mikekazakov** [comment]
Well, I don't see how the issue can be resolved if the underlying library doesn't support this method, sorry.
The best way forward would be to explicitly add support for this filter to libarchive, then it would automatically work in NC as well. Of course it's theoretically possible to have another VFS to work with these archives, but the effort required to implement and maintain it would be beyond reasonable.
