### ISSUE TITLE
[Bug]: FTP incomplete upload/download

### ISSUE THREAD

**Issue by d0ublezer0** [mikekazakov/nimble-commander#292]
### Confirmation

- [X] I have read the contributing guidelines

### Version of Nimble Commander

1.6.0 MacOS 14.5 (23F79)

### Distribution Type

Downloaded directly from the website

### Expected Result

FTP must maintain file integrity

### Actual Result

I tried to upload a text file or jpg to FTP - all the files were not fully uploaded.
On the FTP side, all files (even old ones) are of the wrong size.
Their download is also incomplete.

I tried this on several hosting sites

### Steps to reproduce

1. connect to any ftp
2. try to upload/download
3. compare size and content of files with local or web file manager

**Comment by d0ublezer0** [comment]
oh, fixed in nightly build
https://github.com/mikekazakov/nimble-commander/actions/runs/9394439525

**Comment by mikekazakov** [comment]
I don't remember fixing anything related to FTP since the release of v1.6: https://github.com/mikekazakov/nimble-commander/commits/main/ 
There might be some kind of flakiness, which was introduced in that version.
More data is needed.

**Comment by d0ublezer0** [comment]
> More data is needed.
Ok, I'll try to roll back to 1.6.0 from releases and check again

**Comment by d0ublezer0** [comment]
Hmm, download 1.6.0 4087 - the problem did not appear again

**Comment by d0ublezer0** [comment]
Version 1.6.0 (4094)
The problem is still here.
I don't understand what caused this situation.

**Comment by mikekazakov** [comment]
Looks like I've found the problem, aim to commit a fix this week.

**Comment by mikekazakov** [comment]
Should be fixed now, please try a fresh nightly build.
