### ISSUE TITLE
[Code]: Refactor the key name in the Keychain

### ISSUE THREAD

**Issue by iron-tech-space** [mikekazakov/nimble-commander#300]
### Task Type

Refactoring

### Description

Hello =)
I would like to ask you to make the following edit. I have an SSH proxy server where different servers are hidden by one IP and differ only in port. Current implementation results in password conflict.
<img width="866" alt="Screen" src="https://github.com/mikekazakov/nimble-commander/assets/61494972/74fcccbf-d644-4072-b18c-725c328cedf3">

**Comment by mikekazakov** [comment]
Hi, this looks like a fully-fledged feature.
I agree that distinguishing password's location in the keychain by the port could be useful, and would be ok with such feature, given:
- the same logic applies to other connection types as well;
- default ports are handled too;
- there's an automatic migration procedure that can ensure that no passwords are lost after updating to a version with such distinction;
- all of that is covered with unit tests.

Would you like to work on that?

**Comment by iron-tech-space** [comment]
Oh, I'm ready to try, but I'm afraid I may not have enough skills in C++ and Objective-C++

**Comment by mikekazakov** [comment]
Well, if you want this feature implemented, go for it!
Someone needs to take the initiative, and I won’t have the bandwidth to do so in the foreseeable future.
Feel free to ask any code-related questions in the Development section of Discussions.
