### ISSUE TITLE
[Bug]: cannot add sftp root to favorites

### ISSUE THREAD

**Issue by vladstudio** [mikekazakov/nimble-commander#307]
### Confirmation

- [X] I have read the contributing guidelines

### Version of Nimble Commander

latest, latest

### Distribution Type

Downloaded directly from the website (including Brew)

### Expected Result

when I connect to an SFTP server, I want to be able to add its root folder to favorites

### Actual Result

See how I can add any selected folder, but not the root folder.

https://github.com/mikekazakov/nimble-commander/assets/914320/5c98783a-97d4-4ac7-9e72-51d89f2ecb59

### Steps to reproduce

1. Connect to an SFTP server;
2. Try to add its root folder as favorite.

**Comment by mikekazakov** [comment]
Cmd+B adds the currently selected directory as a favourite, so as it's not possible to focus the VFS root itself - this hotkey can't be used to add it.
You can use the Favourites window instead: hit the "+" button there, it'll drop down a list of currently opened locations regardless of cursor position.
I frankly don't know how to adjust the hotkey-driven UX to allow it.

**Comment by mikekazakov** [comment]
Should be fixed now.
