### ISSUE TITLE
[Bug]: Error on Synology SMB Move to Trash

### ISSUE THREAD

**Issue by derfeznoj** [mikekazakov/nimble-commander#316]
### Confirmation

- [X] I have read the contributing guidelines

### Version of Nimble Commander

Version 1.6.0 (4086)

### Distribution Type

Downloaded from Mac App Store (i.e. sandboxed)

### Expected Result

Delete file/folder either proceeds or has 'do you want to delete?' dialog

### Actual Result

Produces an error "Failed to move an Item to Trash". If you select 'delete permanently' the process proceeds and the deleted items are moved to the Synology NAS recycle bin.

### Steps to reproduce

1. Select file/folder
2. Right click to get contextual menu
3. Select Move to Trash
4. Dialog "Failed to move an Item to Trash"
5. Click 'Delete permanently'

### Additional Information

More of an issue with ambiguity as, now that I know how it works, all iis okay.

**Comment by mikekazakov** [comment]
How to reproduce it without access to Synology hardware?

**Comment by mikekazakov** [comment]
No response - closing.
