### ISSUE TITLE
[Bug]: copy/move/rename folder refresh bug

### ISSUE THREAD

**Issue by pwu7** [mikekazakov/nimble-commander#357]
### Confirmation

- [X] I have read the contributing guidelines

### Version of Nimble Commander

1.6.0 (4121), IOS 14.5 (23F79)

### Distribution Type

Downloaded from GitHub (nightly and test workflows)

### Expected Result

You can freely navigate through folders on target pane during and after copy/move/batch file renaming process

### Actual Result

During copy/move/batch file renaming process (and some time after it) target pane is locket to target folder. If you are trying to change it (go one level up) - it automatically switches back to the first file of target folder.

It happens one time for copy/move operations during copy/move process and some time after it (while small rotating circle icon is running in the pane's corner)

And it happens constantly during batch rename operation (until it finishes and small rotating circle icon disappears) 

Please check this link for screen recording
https://www.dropbox.com/scl/fi/gs3b4ec3rc0of0nkc0mh6/refresh_bug.mov?rlkey=wonti9l2fnvf7tai2d3oj3lw5&dl=0

### Steps to reproduce

1. Select folder with large amount of files
2. Copy/move files to target folder
3. Switch to target pane
4. Try to go one level up from target folder (and you will automatically switched back to the first file in the target folder)

Or the same with batch rename (and it will continuously switch back to the first file in the target folder until renaming will be completed and small rotating circle icon will disappear)

**Comment by mikekazakov** [comment]
Hi, indeed looks like a bug than needs fixing, thanks for reporting.

**Comment by mikekazakov** [comment]
Should be fixed now, please check a fresh nightly build.

**Comment by pwu7** [comment]
just checked, it works great, thank you!

**Comment by mikekazakov** [comment]
Thanks for verifying!
