### ISSUE TITLE
[Bug]: Typo in Settings → Panels → Behaviour: "simulateneous" 

### ISSUE THREAD

**Issue by eirens** [mikekazakov/nimble-commander#369]
### Confirmation

- [X] I have read the contributing guidelines

### Version of Nimble Commander

v1.6.0, macOS

### Distribution Type

Downloaded from Mac App Store (i.e. sandboxed)

### Expected Result

Observed: "simulateneous"

### Actual Result

Correct: "simultaneous"

### Steps to reproduce

1. Go to _Settings → Panels → Behaviour_.
2. Read label name.
<img width="842" alt="Screenshot 2024-09-05 at 6 05 44 PM" src="https://github.com/user-attachments/assets/94f719c3-370b-416a-9a48-6fb3245fda9d">

**Comment by mikekazakov** [comment]
Good catch, thanks!
