### ISSUE TITLE
[UI]: Polish - Decrease the height of the separator in the list view header 

### ISSUE THREAD

**Issue by mikekazakov** [mikekazakov/nimble-commander#395]
### Confirmation

- [X] I have read the contributing guidelines.

### Version of Nimble Commander

v1.7, macOS 15

### Current Appearance

<img width="429" alt="Screenshot 2024-09-23 at 19 15 22" src="https://github.com/user-attachments/assets/f4118659-14b4-4c25-a2d3-fc654414cfb2">

Currently the header separators are 22px tall, with 2px gaps at the top and the bottom.

### Expected Appearance

<img width="246" alt="Screenshot 2024-09-23 at 19 16 49" src="https://github.com/user-attachments/assets/62797cc3-3ede-4683-bc2c-0885394a8fbc">

Looks like they are now 19px tall on MacOS with 3px gaps. It looks lighter (putting aside the used color).

### Additional Information

Change the vertical gaps: 2px -> 3px in `[PanelListViewTableHeaderCell drawVerticalSeparatorWithFrame]`.

**Comment by brown-eric** [comment]
Hey! I would like to help with this issue if possible. What are the destination folder and files that are needing to be changed?

**Comment by mikekazakov** [comment]
Hi, sure, the line that needs to be changed is this one:
https://github.com/mikekazakov/nimble-commander/blob/e5e034557eb6d6ac2b7a460723f7b229c315ea44/Source/NimbleCommander/NimbleCommander/States/FilePanels/List/PanelListViewTableHeaderCell.mm#L40

**Comment by brown-eric** [comment]
I'm pretty sure it's fixed now

**Comment by mikekazakov** [comment]
Pardon, what do you mean? There weren't any changes in the source code.
