### ISSUE TITLE
[UI]: Number of found items in search bar could benefit from padding.

### ISSUE THREAD

**Issue by teropentis64** [mikekazakov/nimble-commander#399]
### Confirmation

- [X] I have read the contributing guidelines.

### Version of Nimble Commander

Nightly Build #250, macOS 15.0

### Current Appearance

![befo](https://github.com/user-attachments/assets/5f02542d-01a2-4809-b9e8-4825751daee1)

### Expected Appearance

<img width="596" alt="after" src="https://github.com/user-attachments/assets/93810ebf-80d0-4e70-adb4-fee8ef286e9e">

### Additional Information

Readability of number of found items when searching in current folder could benefit from few pixels padding. **I've moved the number left by 10px** so the space between "x" circle is the same. The number is also a bit darker (not here though, on Expected Appearance screenshot)
![closeup](https://github.com/user-attachments/assets/0fe18d42-7c4c-4399-9426-88c09b2a833a)

**Comment by mikekazakov** [comment]
Agree, it should be a nice refinement.

The gap can be adjusted here:
https://github.com/mikekazakov/nimble-commander/blob/625c67ddc1f5866af8d8fdad3287e97fa8d6b09d/Source/NimbleCommander/NimbleCommander/States/FilePanels/PanelViewHeader.mm#L205

The font colour can be adjusted hereL
https://github.com/mikekazakov/nimble-commander/blob/625c67ddc1f5866af8d8fdad3287e97fa8d6b09d/Source/NimbleCommander/NimbleCommander/States/FilePanels/PanelViewHeader.mm#L88

**Comment by teropentis64** [comment]
Ok, I've set it to:
```objc
[self addConstraints:[NSLayoutConstraint constraintsWithVisualFormat:@"[m_SearchMatchesField(==50)]-(25)-|"
```
and
```objc
m_SearchMatchesField.textColor = [NSColor systemGrayColor];
```
the results are:
![result](https://github.com/user-attachments/assets/43b4a4d0-eadf-4ecf-8b71-db6a2061e8e5)

**Comment by mikekazakov** [comment]
Thank you. How does it look in the Dark mode? The (relatively) fixed colours might be a bit problematic as they do not "invert" when the appearance changes. For the grey colour it might be less relevant, but still.

**Comment by mikekazakov** [comment]
Done, thanks!
