### ISSUE TITLE
[UI]: Refreshed icon project

### ISSUE THREAD

**Issue by teropentis64** [mikekazakov/nimble-commander#400]
### Confirmation

- [X] I have read the contributing guidelines.

### Version of Nimble Commander

Nimble 1.6.1

### Current Appearance

<img width="351" alt="dock old" src="https://github.com/user-attachments/assets/8fe0afd5-7e89-414f-ad1f-5d1b6622919b">

### Expected Appearance

![dock](https://github.com/user-attachments/assets/901bd195-0753-4f31-8830-9fb7c444ecd3)

### Additional Information

I've made a project for myself and thought I might share, maybe it will become useful for at least few people. Nothing too crazy, just refreshed the original icon to the more recent design. Made with official macOS icon template. No stock assets used.
![mission](https://github.com/user-attachments/assets/8215f0e8-6e9f-49c4-a624-0c5d5ca1a16c)
![preview](https://github.com/user-attachments/assets/3050e267-c748-4b6d-82f9-f15484f76ae6)
[Nimble-Commander.iconset.zip](https://github.com/user-attachments/files/17137418/Nimble-Commander.iconset.zip)

**Comment by mikekazakov** [comment]
Wow, thanks, that looks great! I'm not an expert in graphics, could you tell about the reasoning behind the changes?

**Comment by teropentis64** [comment]
The icon ? I think it may be a bit outdated in regards to new designs. Thats just my opinion though.

**Comment by mikekazakov** [comment]
I quite like the refreshed original icon (the first one in this issue) and think it would be nice to use as a default app's icon.
If you are ok with it - please feel free to make a pull request replacing the icon in the repository.
Alternatively I can do it myself.

**Comment by teropentis64** [comment]
No problem, use whatever You want. I would prefer You to do it though as I use GitHub mainly to just report various bugs... I don't code that much.

**Comment by mikekazakov** [comment]
Done, thanks for the contribution!
