### ISSUE TITLE
[UI]: App titlebar blur effect not consistent across views.

### ISSUE THREAD

**Issue by teropentis64** [mikekazakov/nimble-commander#406]
### Confirmation

- [X] I have read the contributing guidelines.

### Version of Nimble Commander

1.6.1

### Current Appearance

<img width="580" alt="desk" src="https://github.com/user-attachments/assets/876ee78c-80e4-4fcb-a600-62b6ca8cddf1">

### Expected Appearance

<img width="580" alt="desknew" src="https://github.com/user-attachments/assets/9e78b3d4-3da7-443e-ba9f-6fec09a666f7">

### Additional Information

The titlebar when console is open has "blur" effect, which is not visible in standard file manager view. Just a little detail that could make it more consistent.

Here's the solid titlebar in standard file manager view:
<img width="580" alt="std" src="https://github.com/user-attachments/assets/adf9ba44-0a02-4618-9fdf-80ca98c6e0aa">

**Comment by mikekazakov** [comment]
Good catch, thanks for reporting. I assume the built-in viewer has the same issue?

**Comment by teropentis64** [comment]
What do you mean? The quicklook on spacebar key? I spotted the blur effect only in console view.

**Comment by mikekazakov** [comment]
No-no, not QuickLook-based, the "built-in viewer" opened by Alt+F3, if it's configured to use the same window, of course. Actually, an external editor running in a terminal (say vi or mcedit) might have the same issue too.

**Comment by mikekazakov** [comment]
I've looked into the issue and can't reproduce it on my side.
My recollection of the things was wrong - terminal app state has its dedicated overlay colour, which is responsible for the tint of the titlebar. This setting seem to work as expected in my experiments, e.g. here's an example:

<img width="850" alt="Screenshot 2024-10-05 at 19 52 33" src="https://github.com/user-attachments/assets/dce3010e-3afc-4e2d-b806-6c23c1ada26e">

What settings does your theme have for the terminal?

**Comment by teropentis64** [comment]
Oh my, You're actually right, that was Overlay color. When I was adjusting my theme I changed it to blue. I would never guess that "Overlay" corresponds to titlebar blur. Sorry about that.

**Comment by mikekazakov** [comment]
No worries. Hopefully one day these settings will be properly described in the user guide :)
