### ISSUE TITLE
[Code]: Moving file to trash in Admin mode results in permanent deletion.

### ISSUE THREAD

**Issue by teropentis64** [mikekazakov/nimble-commander#417]
### Task Type

Technical Debt

### Description

Just as in title, deleting file in Admin mode doesn't move the file to trash but instead permanently deletes it without undo action. Maybe if the implementation for moving file to trash in Admin mode is tricky - at least add a popup window to confirm deletion. Sometimes navigating fast through folders and deleting unnecessary files results in accidental file deletion.

**Comment by mikekazakov** [comment]
It does move the file to trash, but perhaps not the intuitively expected trash folder.
When the admin mode is on, such file operations are effectively performed using the root account, hence the item is moved to... the root's trash folder.
This directory is normally located at `/var/root/.Trash`.

**Comment by teropentis64** [comment]
Thanks, I didn't know that. I know Nimble is more oriented towards power users, but is moving file to root Trash folder necessary ? I doubt anyone is keeping track of 2 trash folders. In addition, root trash folder is tricky to access. Just an idea though, thanks!

**Comment by mikekazakov** [comment]
I agree that the current behaviour may look strange.
On the other hand - I'm not exactly sure how a correct and an intuitively expected behaviour should look like instead.

**Comment by teropentis64** [comment]
Well, I think when user deletes file to Trash he expects the file will go to trash which he is the most familiar with, the user one. But maybe I'm biased, do You use the root trash folder ?

**Comment by mikekazakov** [comment]
No, I don't normally use the root's trash folder.

This expectation makes sense, but let's imagine a more complex scenario:
- Bob turns on the Admin Mode
- Bob goes into Alice's documents and moves some of it to trash.
- There Alices' files are expected to be afterwards - Bob's Trash, Alice's Trash or root's Trash?

What NC does when moving to trash with Admin Mode On is effectively:
```
sudo su
trash /path/to/file
# let's pretend that macOS actually ships something like a trash command
# or alternatively it's from e.g. https://formulae.brew.sh/formula/trash 
```
When looking from this angle, it's much less obvious that the trashed file should land into the trash folder of the user which executed `sudo`.

I think that generally Admin Mode should be used very extreme caution - the red "ADMIN" badge is shown on the NC's icon for that reason.

**Comment by teropentis64** [comment]
Well, hopefully in some future there will be an option to moves files to trash of current user. 

My question originates from that I've never seen such behaviour from file manager app. I do a lot of operations on files that need root access so changing permission for every single file I need to delete would be just annoying.

**Comment by eugenesvk** [comment]
> * Bob goes into Alice's documents and moves some of it to trash.
> * There Alices' files are expected to be afterwards - Bob's Trash, Alice's Trash or root's Trash?

Certainly Bob's. Trash belongs to the user doing the Trashing! I don't get how Alice changes anything here, it's the same if Bob's trashing some system files - they should all move to Bob's trash, not root's trash.

The only (or at least the main one for most of the use cases) reason to use root account here is convenience (to avoid multiple permissions prompts), nothing more, so it's identical to giving admin permissions for each operations, which results in files moving to Bob's trash bin.

**Comment by mikekazakov** [comment]
> Certainly Bob's. Trash belongs to the user doing the Trashing! I don't get how Alice changes anything here, it's the same if Bob's trashing some system files - they should all move to Bob's trash, not root's trash.
> 
> The only (or at least the main one for most of the use cases) reason to use root account here is convenience (to avoid multiple permissions prompts), nothing more, so it's identical to giving admin permissions for each operations, which results in files moving to Bob's trash bin.

If you're aware of a way to actually implement this behaviour in practice - please share an insight.

**Comment by eugenesvk** [comment]
(is it possible to ask for admin permissions once and retain the entitlement? Maybe this could be an alternative "admin" mode that would use user's trashes by default, just avoid the need to ask for admin multiple time)

What about this? 
- when entering admin mode, remember the current user ID/name
- when trashing files, get the trash dir path for the remembered user ID/name
  - create it with user's permissions if it's missing
- move files to that trash dir instead of using the current FileManager api that would use root's trash dir since we're root

Bonus: 
- update Ds_store database to add newly deleted files there to allow Finder's 'put back' functionality (would also resolve https://github.com/mikekazakov/nimble-commander/discussions/452)

**Comment by mikekazakov** [comment]
> (is it possible to ask for admin permissions once and retain the entitlement? Maybe this could be an alternative "admin" mode that would use user's trashes by default, just avoid the need to ask for admin multiple time)

In the MacOS security model there's no additional entitlements for the running application itself.
After authenticating with an admin user's password, it allows to either install a privileged helper (that's what NC does) or to start another program with elevated rights (which Apple has been deprecating for a long time).
The running application itself doesn't get any additional permissions regarding filesystem operations.

The Admin mode in NC works by redirecting the I/O requests by IPC to the privileged helper that runs under the root credentials - hence the unexpected trashing behaviour.

The reason NC asks to authenticate as admin after the privileged helper was installed is purely courtesy - in principle NC can communicate with it at any point without asking to re-authenticate, but that would be too insecure.

> What about this?
> 
> * when entering admin mode, remember the current user ID/name
> * when trashing files, get the trash dir path for the remembered user ID/name
>    * create it with user's permissions if it's missing
> * move files to that trash dir instead of using the current FileManager api that would use root's trash dir since we're root
> 
> Bonus:
>
> * update Ds_store database to add newly deleted files there to allow Finder's 'put back' functionality (would also resolve https://github.com/mikekazakov/nimble-commander/discussions/452)

Currently NC doesn't move the files manually to the Trash folder, it delegates this operation to MacOS, which in turn doesn't allow to specify to how moving to Trash is done - it's a black box:  https://developer.apple.com/documentation/foundation/filemanager/trashitem(at:resultingitemurl:)?language=objc.

In theory I guess it's possible to write a trashing procedure, but the contracts are rather opaque (e.g. how name conflicts are resolved? etc) and it can become a giant can of worms which must be maintained.
DS_Store is equally undocumented and can change at any point.

**Comment by eugenesvk** [comment]
> or to start another program with elevated rights

That’s the same as running as root, right? So launching an NC instance with elevated rights wouldn't help, it'd still use root trash?

> but the contracts are rather opaque (e.g. how name conflicts are resolved? etc)

Contacts with which app/service?? Suppose you make up arbitrary resolution rule or move every batch in a separate dir, who is expecting you to stick to a scheme? The file manager API doesn't care?

> DS_Store is equally undocumented and can change at any point.

But has it changed at any point? Not that easy to change, I think, given that different OS versions can trash to the same destination (external drives) 

Anyway, that's version-gated risk, maybe disable with a warning on OS versions NC hasn't been tested with and require user override? Or you could just maintain your own database for undo purposes and not have it be compatible with Finder, though that's losing a nice benefit

**Comment by mikekazakov** [comment]
> > or to start another program with elevated rights
> 
> That’s the same as running as root, right? So launching an NC instance with elevated rights wouldn't help, it'd still use root trash?

That's right, effectively it's like running with "user=root".

> > but the contracts are rather opaque (e.g. how name conflicts are resolved? etc)
> 
> Contacts with which app/service?? Suppose you make up arbitrary resolution rule or move every batch in a separate dir, who is expecting you to stick to a scheme? The file manager API doesn't care?

Contract of the Trash folder. It should contain quite a lot of metadata and likely follow some rules to be consistent.

> > DS_Store is equally undocumented and can change at any point.
> 
> But has it changed at any point? Not that easy to change, I think, given that different OS versions can trash to the same destination (external drives)

I'm pretty sure it does change quite a lot over the years.

> Anyway, that's version-gated risk, maybe disable with a warning on OS versions NC hasn't been tested with and require user override? Or you could just maintain your own database for undo purposes and not have it be compatible with Finder, though that's losing a nice benefit

Adding more functionality to NC which will require a per-version maintenance is just a no-go - I don't have time for such support.

It seems that the only right solution would be to remove this admin trashing functionality entirely, and instead do a permanent deletion after showing a confirmation dialog.
