### ISSUE TITLE
[UI]: Button in file deletion dialog could benefit from padding.

### ISSUE THREAD

**Issue by teropentis64** [mikekazakov/nimble-commander#418]
### Confirmation

- [X] I have read the contributing guidelines.

### Version of Nimble Commander

Nimble 1.7

### Current Appearance

![1](https://github.com/user-attachments/assets/73a135ce-b1ed-413a-a4ed-f76fcf43b404)

### Expected Appearance

<img width="431" alt="2" src="https://github.com/user-attachments/assets/353364d4-5dc1-455a-8197-8b534829bf4d">

### Additional Information

Just as with #396, but this one may need a bit more padding as it's overlapped by few pixels by "Move to trash" button.

**Comment by mikekazakov** [comment]
Should be fixed now.
