### ISSUE TITLE
[UI]: Unnecessary wrapping of the checkbox label in the File Attributes dialog

### ISSUE THREAD

**Issue by mikekazakov** [mikekazakov/nimble-commander#427]
### Confirmation

- [X] I have read the contributing guidelines.

### Version of Nimble Commander

v1.7, macOS15

### Current Appearance

The "Append-only" check box label wraps its text:

<img width="752" alt="Screenshot 2024-10-13 at 12 33 32" src="https://github.com/user-attachments/assets/57c4757a-8032-4c39-b878-77ac19e0af57">

### Expected Appearance

Both columns should be wide enough to fit the checkboxes without wrapping their labels.

**Comment by fabsantana** [comment]
Hello! Just submitted a PR for this issue. :-) https://github.com/mikekazakov/nimble-commander/pull/428

**Comment by mikekazakov** [comment]
Hey, thanks, I've just reviewed it.

**Comment by mikekazakov** [comment]
Fixed by #428.
