### ISSUE TITLE
[Bug]: Broken search in files behavior

### ISSUE THREAD

**Issue by alexey-lysiuk** [mikekazakov/nimble-commander#482]
### Confirmation

- [X] I have read the contributing guidelines

### Version of Nimble Commander

v1.7.0

### Distribution Type

Downloaded directly from the website (including Brew)

### Expected Result

Search should return only files with the provided text in them.

### Actual Result

*Containing text* field is cleared, and all files are displayed as search result.

### Steps to reproduce

* Start Nimble Commander
* Press `Cmd+F` or select *Find...* item in *File* menu
* Type or paste any string into *Containing* text field
* Press Enter or click *Search* button
* *Containing text* field is cleared, and all files are displayed as search result

### Additional Information

After several attempts, search begins to function as expected with no apparent indication what action fixed it exactly.
The next time Nimble Commander is launched, the issue appears again.

The bug seems to be introduced in version 1.7.0.

**Comment by mikekazakov** [comment]
Hi, I can't reproduce it on my machine(s) - there has to be something more in the issue.

**Comment by alexey-lysiuk** [comment]
It works if previous search string is selected from drop down list. In this case, if a new string is entered, and then *Search* button is pressed, field resets its text to old one.

**Comment by alexey-lysiuk** [comment]
I exited NC, renamed `~/Library/Application Support/Nimble Commander`, and launched again. The issue still persists for me.
As a test case, I entered NC app bundle, and did a search for `CFBundleIdentifier` string. All files were reported as the result.
Search strings were not added to history drop down list, it contained *Options* group only.

**Comment by mikekazakov** [comment]
It's likely not about the existing settings - I've just installed a pristine macOS 15.2 in a VM and tried the release build v1.7, but again the UI behaved as expected. You can try running from a terminal to check if there are any messages there, same with the built-in Log window. In the worst-case scenario you can build NC from source and run under the Xcode's debugger.

**Comment by alexey-lysiuk** [comment]
I saw no related message in Console.app logs.

Search in files works only when keyboard focus is changed from *Containing text* field before pressing Return or clicking *Search* button. Otherwise, `textSearchField` is set to previous value in `[FindFilesSheetController OnSearch]`, e.g., it remains empty if there was no searches before.

**Comment by alexey-lysiuk** [comment]
> * Does the file mask text field show any related symptoms? This two search fields are almost identical in the way they are integrated.

File mask works correctly, only _Containing text_ field is affected.

> * Which version of MacOS are you running? Is Apple Intelligence enabled on your machine?

15.2 on Intel, so Apple Intelligence is not available.

> * If you try creating a new fresh user and repeating the same with the new account - does it show the same issue?

Nothing changed with the new user account, file mask does work while text search is still broken.

**Comment by mikekazakov** [comment]
Got it, thank you for the additional information.
I managed to finally reproduce the issue on my side!
In my case though it only happens when clicking on the Search button with a mouse, which I never do normally - always use the Return key for that.

**Comment by mikekazakov** [comment]
Can you check if this change https://github.com/mikekazakov/nimble-commander/commit/7a5d28b3e6951532095420a3e3e0b1b32e196c48 fixes the issue for you?

**Comment by alexey-lysiuk** [comment]
This change fixes the issue.

**Comment by mikekazakov** [comment]
Good, I've merged the change into `main`. Hopefully it'll become clearer later why is this happening.
