### ISSUE TITLE
[UI]: Dropdown for Goto-Location appears on different screen

### ISSUE THREAD

**Issue by simonsolutions** [mikekazakov/nimble-commander#485]
### Confirmation

- [X] I have read the contributing guidelines.

### Version of Nimble Commander

1.7.0

### Current Appearance

With the new release the goto-dropdown shows on a different screen (i have 3 external screens). The position is approximately the correct one just the wrong screen.  

### Expected Appearance

Show the dropdown on the right screen

### Additional Information

The DisplayLink Manager is used for the docking station where the displays are connected.
https://www.synaptics.com/products/displaylink-graphics/downloads/macos
The current version is installed on the system. 
macOS is also the newest version 15.2. It is a Macbook Pro M2 Max.

**Comment by mikekazakov** [comment]
Thanks for reporting, I confirm the issue.

**Comment by mikekazakov** [comment]
Should be fixed now, please check the next nightly build.

**Comment by simonsolutions** [comment]
Works now again. Thanks for the quick fix
