### ISSUE TITLE
Failed to access the privileged helper

### ISSUE THREAD

**Issue by ronaldsuwandi** [mikekazakov/nimble-commander#72]
Running version 1.2.2 (2449) on MacOS High Sierra (10.13.1) non-MAS version

I tried to follow the instructions on the forum http://magnumbytes.com/forum/viewtopic.php?t=63 but still doesn't work - after entering my username & password I still get the error

**Comment by mikekazakov** [comment]
Did it install the helper into /Library/LaunchDaemons/ and /Library/PrivilegedHelperTools/?

**Comment by ronaldsuwandi** [comment]
Nope...

```
~ ☕️  ll /Library/PrivilegedHelperTools/
total 7560
-r-xr--r--  1 root  wheel    43K Oct  4 16:25 com.docker.vmnetd*
-r-xr--r--  1 root  wheel   3.6M Aug 22 09:54 com.nordvpn.NordVPN.Helper*
-r-xr--r--  1 root  wheel    33K Jan 13  2016 com.surteesstudios.Bartender.BartenderInstallHelper*
-r-xr--r--@ 1 root  wheel    31K Nov 27 14:25 info.filesmanager.Files.PrivilegedIOHelperV2*
~ ☕️  ll /Library/LaunchDaemons/
total 72
-rw-r--r--  1 root  wheel   446B Nov 17 12:11 com.apple.installer.cleanupinstaller.plist
-rw-r--r--  1 root  wheel   688B Oct  4 16:25 com.docker.vmnetd.plist
-rw-r--r--@ 1 root  wheel   818B Oct 13 09:39 com.google.keystone.daemon.plist
-rw-r--r--  1 root  wheel   564B Aug 22 09:54 com.nordvpn.NordVPN.Helper.plist
lrwxr-xr-x  1 root  wheel   103B Jul  1  2015 com.oracle.java.Helper-Tool.plist@ -> /Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Resources/com.oracle.java.Helper-Tool.plist
-rw-r--r--  1 root  wheel   664B Jan 13  2016 com.surteesstudios.Bartender.BartenderInstallHelper.plist
-rw-r--r--  1 root  wheel   667B Nov 27 14:25 info.filesmanager.Files.PrivilegedIOHelperV2.plist
-rw-r--r--  1 root  wheel   516B Feb 20  2017 keybase.Helper.plist
-rw-r--r--  1 root  wheel   544B Jun 21  2016 limit.maxfiles.plist
-rw-r--r--  1 root  wheel   587B Jun 21  2016 limit.maxproc.plist
lrwxr-xr-x  1 root  wheel    76B Nov 27 14:58 org.virtualbox.startup.plist@ -> ../Application Support/VirtualBox/LaunchDaemons/org.virtualbox.startup.plist
```

**Comment by mikekazakov** [comment]
Wait a sec... but it did.
NC still uses "info.filesmanager.Files" BundleID due to historical reasons.
Next question - did this helper start?
Also, it provides some logging in Console - maybe there's something suspicious there.

**Comment by ronaldsuwandi** [comment]
![image](https://user-images.githubusercontent.com/4120788/33707199-96fee6ac-db71-11e7-953b-38d9946bbdda.png)

I tried to look through Console but no luck

How do I check if the helper start? When I tried to enable privilege helper it just failed (Unable to start)

**Comment by mikekazakov** [comment]
It should be visible in processes list (like in Activity Monitor).
I'll soon release the v1.2.3 of NC, which contains an additional logging regarding communication with the privileged helper, it should make it clear.

**Comment by ronaldsuwandi** [comment]
Thanks! Currently I can't see it in the Activity Monitor (filtering for both "privilege" and "helper" yields no result). Will wait for 1.2.3 and see how it goes :-)

**Comment by ronaldsuwandi** [comment]
Tried it on 1.2.3 and it's all good now 👍
