### ISSUE TITLE
Sometimes font is not shown correctly

### ISSUE THREAD

**Issue by ronaldsuwandi** [mikekazakov/nimble-commander#73]
![image](https://user-images.githubusercontent.com/4120788/33877770-547c66f0-df64-11e7-963a-84851098bba6.png)

Right pane - font is blurry

![image](https://user-images.githubusercontent.com/4120788/33877799-731a6b3e-df64-11e7-83c5-1aad12930255.png)
But when switch to another tab, the font looks normal

**Comment by mikekazakov** [comment]
Any ideas how to reproduce this behavior?

**Comment by ronaldsuwandi** [comment]
not really, looks like macos bug though, it happened to Marta as well

restarting NC fixed it, probably something to do with the macbook going to sleep... I'll just close this ticket for now
