### ISSUE TITLE
Symlinks to network resources open in a new Finder window

### ISSUE THREAD

**Issue by lookfortheroot** [mikekazakov/nimble-commander#75]

**Comment by mikekazakov** [comment]
Could you elaborate?

**Comment by lookfortheroot** [comment]
I checked twice and now I see, this happens only when a symlink refers on the folder in a network drive.

When I press Enter, then instead entering in as usual folder, a new Finder window opens with this folder's content.

**Comment by mikekazakov** [comment]
I can't reproduce this behavior. Any additional info?

**Comment by lookfortheroot** [comment]
It seems that symlink was made in some odd format. When I create new ones (by macOS and Commander), they work as expected.
Besides in the file list bad symlink shows as "file", good ones as "folder". I'ts weird 😒 
Sorry for troubling you and I close this.
