### ISSUE TITLE
Underscore '_' vs. numbers in folders/files sorting

### ISSUE THREAD

**Issue by varrav** [mikekazakov/nimble-commander#85]
Folders with name starting with underscore '_' go after folders with name starting with numbers. F.e. folder '2019_01_01' goes before '_temp', seems should be vice versa - commonly underscore goes first.

**Comment by ershov** [comment]
Sorting order depends on your locale, I guess.

**Comment by mikekazakov** [comment]
Nimble Commander now supports Natural collation, roughly https://en.wikipedia.org/wiki/Unicode_collation_algorithm.
<img width="745" alt="Screenshot 2024-09-08 at 18 23 56" src="https://github.com/user-attachments/assets/eb9774f1-8575-423c-9aa4-7ae5b568b0f2">
