### ISSUE TITLE
Failed SFTP connection

### ISSUE THREAD

**Issue by AuthorProxy** [mikekazakov/nimble-commander#89]
Version 1.4.0 (3883)
Trying to connect to my remote server.

SFTP connection error:
Authentication by key failed

type sftp
name: root
password: <empty>
Set my rsa key file

Every other file manager or ftp app - works with similar connection GUI works, ssh via console works.

**Comment by mikekazakov** [comment]
Need more details to be able to reproduce the issue.

**Comment by yougotwill** [comment]
@mikekazakov I have a similar issue. I have confirmed that I can connect via the terminal and Cyberduck. When I try to connect I get "SFTP Connection Error: Couldn't resolve SFTP server host". Is there a way to get more verbose logs? 

Just stumbled on Nimble Commander recently very happy with it. I appreciate you are moving to a free plan but I thought I would still purchase to support development. Would appreciate the SFTP support getting looked at as it is the last thing I need to make the go ahead and purchase 🙏

**Comment by mikekazakov** [comment]
Hi, by any chance is the host accessible via IPv6? At the moment the implementation supports only IPv4.

**Comment by yougotwill** [comment]
> Hi, by any chance is the host accessible via IPv6? At the moment the implementation supports only IPv4.

Hi, actually it turns out it was probably because the free trial expired. I tested with a fresh install and it worked fine. Although it is a little slow when moving between folders. It's also good to know that IPv6 isn't supported yet.

I'm buying my license as we speak. Keep up the awesome work! 🙏
