### ISSUE TITLE
Open Encrypted RAR Archive

### ISSUE THREAD

**Issue by MrZigi** [mikekazakov/nimble-commander#92]
Hello NC Fans,

do you also observe an issue when trying to open encrypted RAR archive in the panel?
Depending on the version of archiving format:
- either nothing happens (ver. 5) or 
- the password prompt pops but nothing happens after entering it (ver. 4).
No such issue for encrypted ZIP archive.

Thanks & best regards,
Zigi

**Comment by mikekazakov** [comment]
Encrypted RAR archives are not supported: https://github.com/libarchive/libarchive/issues/1443

**Comment by MrZigi** [comment]
So it'd macOS again ;) Thanks!
