### ISSUE TITLE
Ability to change the date format in date columns

### ISSUE THREAD

**Issue by formatq** [mikekazakov/nimble-commander#93]
Hello, I am a new user of Nimble-Commander. 

I want to use a custom time format (e.g. YYYYY-MM-DD HH:MM:ss) for the time columns.

I tried to change this time format in System Preferences. I did it as follows:
```
defaults write -g AppleICUDateFormatStrings -dict-add "1" "dd.MM.yyyy"  
defaults write -g AppleICUDateFormatStrings -dict-add "2" "dd.MM.yyyy"  
defaults write -g AppleICUDateFormatStrings -dict-add "3" "dd.MM.yyyy"  
defaults write -g AppleICUDateFormatStrings -dict-add "4" "dd.MM.yyyy"  

defaults write -g AppleICUTimeFormatStrings -dict-add "1" "HH:mm:ss"  
defaults write -g AppleICUTimeFormatStrings -dict-add "2" "HH:mm:ss"  
defaults write -g AppleICUTimeFormatStrings -dict-add "3" "HH:mm:ss"  
defaults write -g AppleICUTimeFormatStrings -dict-add "4" "HH:mm:ss"
```

My Finder displays the date and time fine, but not in Nimble Commander. 

Could you please add the ability to change the time format in Nimble Commander?

Thanks

**Comment by formatq** [comment]
shows this, added Finder for comparison:
<img width="801" alt="image" src="https://github.com/mikekazakov/nimble-commander/assets/3082584/ad418f18-501f-4e20-b5f1-dc00fec921d5">

Yep, I restarted it.

**Comment by mikekazakov** [comment]
How would NC look if you resize the columns with the dates to allow more space to be used?

**Comment by formatq** [comment]
omg, yeah, it works. 
The time appears after resizing. 
Thank you!
